[% 
  page.title = 'Demos' 
  page.tab = 'demo'
  page.nocrumbs = 1 
%]


<h2>Submission Sifting</h2>

<div>
<a href="[% site.url %]/demo/sift" alt="Demo: SubSift REST API Explorer">
  <img src="[% site.media %]/img/demo/sift.png" style="float: left; margin-bottom: 20px; padding: 10px 40px 0px 0;" />
</a>
</div>


<p>Match conference reviewers to submitted papers.
  Build profiles of reviewers and papers.
  Then compare these profiles to generate personalised web pages listing ranked papers and initial bid assignments for each of the reviewers.
  </p>

<p><strong>Demo:</strong> <a href="[% site.url %]/demo/sift">Submission Sifting</a></p>

<br />
<br />


<h2>SubSift REST API Explorer</h2>

<div>
<a href="[% site.url %]/demo/explorer" alt="Demo: SubSift REST API Explorer">
  <img src="[% site.media %]/img/demo/subsift_explorer.png" style="float: left; margin-bottom: 20px; padding: 10px 40px 0px 0;" />
</a>
</div>


<p>Use the SubSift REST API Explorer web page, in conjunction with the <a href="[% site.url %]/api">API documentation</a>, to interactively experiment with the SubSift REST API in a Web 2.0 context. As well as being a useful tool in its own right, the SubSift REST API Explorer demonstrates how to access API methods from an HTML page using JavaScript. Inspect the page source of the demo to see how the code works. Further details of how to use SubSift with JavaScript are covered in API documention section: <a href="[% site.url %]/api/examples-javascript">Examples - JavaScript</a>.</p>

<p><strong>Demo:</strong> <a href="[% site.url %]/demo/explorer">SubSift REST API Explorer</a></p>

<br />
<br />


<h2>ILRT Matcher</h2>

<div>
<a href="[% site.url %]/demo/ilrt_matcher" alt="Demo: ILRT Matcher">
  <img src="[% site.media %]/img/demo/ilrt_matcher.png" style="float: left; margin-bottom: 20px; padding: 10px 40px 0px 0;" />
</a>
</div>

<p>Enter keywords or the text of an abstract or article to find the closest matching person in an organisation, based on textual similarity to staff homepages.
The results are displayed as a bar chart, optionally including the list of terms that contribute to the similarity scores.
The organisation in this demo is <a href="http://www.ilrt.bris.ac.uk" class="external">ILRT</a>, but the design pattern is generic.</p>

<p><strong>Demo:</strong> <a href="[% site.url %]/demo/ilrt_matcher">ILRT Matcher</a></p>

<br />
<br />


<h2>DBLP Author Finder</h2>

<div>
<a href="[% site.url %]/demo/dblp_search" alt="Demo: DBLP Author Finder">
  <img src="[% site.media %]/img/demo/dblp_search.png" style="float: left; margin-bottom: 20px; padding: 10px 40px 0px 0;" />
</a>
</div>

<p>Enter a list of the names of academic authors and search for possible author pages in the <a href="http://www.informatik.uni-trier.de/~ley/db/" target="dblp" class="external">DBLP</a> bibliographic database. The purpose of this demo is to make it easy to build lists of urls for bibliographic web pages of potential conference/journal paper reviewers. A bibliographic web page lists the titles of the publications of an academic author and in that sense represents their expertise and interests.</p>

<p><strong>Demo:</strong> <a href="[% site.url %]/demo/dblp_search">DBLP Author Finder</a></p>

<br />
<br />

