<div id="content">
  
<h3 id="research-news">[% report.description %]</h3>

<p>
<object data="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].svg" type="image/svg+xml" width="800" height="600" />
</p>


<div id="news-article-further-info">
  <h2>
    Downloads:
  </h2>
<p>Alternative diagram formats:</p>
<ul>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].pdf" target="_new">[% matches.id %].pdf</a></li>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].png" target="_new">[% matches.id %].png</a></li>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].jpg" target="_new">[% matches.id %].jpg</a></li>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].svg" target="_new">[% matches.id %].svg</a></li>
</ul>
<p>Diagram data files (in <a href="http://www.graphviz.org/" target="_new">Graphviz</a> format):</p>
<ul>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %].dot" target="_new">[% matches.id %].dot</a></li>
<li><a href="[% site.url %]/[% site.user_id %]/reports/[% folder_id %]/[% matches.id %]_interactive.dot" target="_new">[% matches.id %]_interactive.dot</a></li>
</ul>
</div>


</div>