<h3>Profile: [% profile.description %]</h3>

[% FOREACH topic IN profile.term %]
<p></p>
	<table width="350px">
	 	  <tr>
		    <th style="text-align: left;">Topic Semantic Space</th>
		    <th style="text-align: right;">#</th>
		    <th style="text-align: right;">weights</th>
		    <th style="text-align: right;">P(t)</th>
		  </tr>
		  [% FOREACH term IN topic %]
		    <tr>
		      <td>[% term.name %]</td>
		      <td style="text-align: right;">[% term.n %]</td>
		      <td style="text-align: right;">[% FILTER format('%.5lf') %][% term.weight %][% END %]</td>
		      <td style="text-align: right;">[% FILTER format('%.5lf') %][% term.p %][% END %]</td>
		    </tr>
		  [% END %]  
	</table>
[% END %] 

<p>
  <strong>Source:</strong><br/>
  <a href="[% profile.source %]">[% profile.source %]</a>
</p>

