[% 
  page.title = 'About SubSift'
%]

<p>SubSift is an innovative "submission sifting" application developed by the Intelligent Systems group at the University of Bristol to support academic peer review. SubSift matches submitted conference or journal papers to potential peer reviewers based on their similarity to published works of prospective reviewers in online bibliographic databases, such as Google Scholar. In the JISC Rapid Innovations (JISCRI) funded, SubSift Services project, the ILRT will redevelop SubSift into a collection of web services designed to support not only peer review but also personalised data discovery and mashups in tools like Yahoo! Pipes.</p>

<p>Further details appear in the opening post of this blog:
<a href="[% site.url %]/blog/project-funded/">SubSift Services project funded under JISC Rapid Innovations</a></p>

<p>To find out more, please contact <a href="http://simonprice.info" class="external">Simon Price</a>.</p>

