[% 
  page.title = 'Documentation' 
  page.tab = 'doc'
%]


<h2>User Guide</h2>

<p>
  <a href="[% site.url %]/api/" style="float:right;padding-left:70px;padding-top:10px;"><img src="[% site.media %]/img/api.png" width="240" height="278" alt="API Methods" /></a>
  SubSift has an <a href="http://en.wikipedia.org/wiki/Application_programming_interface" class="external">Application Programming Interface (API)</a> which allows the functionality of SubSift to be incorporated into other software.
  The SubSift API follows the design principles of <a href="http://en.wikipedia.org/wiki/Representational_State_Transfer" class="external">Representational State Transfer (REST)</a>.
  Detailed reference documentation of all the API methods is available from the API link at the top of the page, or from the following link.</p>
<ul>
<li><a href="[% site.url %]/api/">API Methods</a></li>
</ul>

<p>Documentation on how to use the API is available from the following links.</p>

<ul>
<li><a href="[% site.url %]/api/formats">Return Formats</a></li>
<li><a href="[% site.url %]/api/http-methods">HTTP Request Methods</a></li>
<li><a href="[% site.url %]/api/response-codes-and-errors">Response Codes and Errors</a></li>
<li><a href="[% site.url %]/api/return-values">Return Values</a></li>
<li><a href="[% site.url %]/api/calling-methods">Calling Methods</a></li>
</ul>

<!--
<h3 class="api"><a href="[% site.url %]/api/terms-of-service">Terms of Service</a></h3>
<p>SubSift is free but please read the terms under which the service is offered.</p>
-->

<p>Currently, the most detailed tutorial on how to use SubSift is published in the FGCS journal paper below.</p>

<h2>Publications</h2>

<table>
  <tr>
    <td width="200">
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001464"><img src="[% site.media %]/img/fgcs.jpg" width="136" height="171" alt="FGCS" /></a>
    </td>
    <td width="200">
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001258"><img src="[% site.media %]/img/ieee_escience_2010.jpg" width="132" height="171" alt="IEEE eScience 2010" /></a>
    </td>
    <td width="200">
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001223"><img src="[% site.media %]/img/jmlr.jpg" width="132" height="171" alt="Journal of Machine Learning Research" /></a>
    </td>
    <td width="200">
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001111"><img src="[% site.media %]/img/blog/cover_full.jpg" width="132" height="171" alt="KDD Explorations" /></a>
    </td>
  </tr>
  <tr>
    <td>
      <p>
      Price, S, Flach, PA, Spiegler, SR, Bailey, CP &amp; Rogers, N., 
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001464"><strong>SubSift web services and workflows for profiling and comparing scientists and their published works</strong></a>. <em>Future Generation Computing Systems</em>. 29(2), (pp. 569–581), February 2012.
      </p>
    </td>
    <td>
      <p>
    Price, S, Flach, PA, Spiegler, SR, Bailey, CP &amp; Rogers, N.,
    <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001258"><strong>SubSift web services and workflows for profiling and comparing scientists and their published works</strong></a>, <em>6th IEEE International Conference on e-Science (e-Science 2010)</em>, Brisbane, Australia, (pp. 182-189), 2010.
      </p>
    </td>
    <td>
      <p>
      Price, S, Flach, PA &amp; Spiegler, S.,
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001223"><strong>SubSift: a novel application of the vector space model to support the academic peer review process</strong></a>, Workshop on Applications of Pattern Analysis (WAPA 2010), <em>JMLR Workshop and Conference Proceedings</em>, 11, (pp. 20-27), 2010.
      </p>
    </td>
    <td>
      <p>
      Flach, PA, Spiegler, SR, Golenia, BSG, Price, S, Guiver, J, Herbrich, R, Graepel, T &amp; Zaki, MJ.
      <a href="http://www.cs.bris.ac.uk/Publications/pub_master.jsp?id=2001111"><strong>Novel Tools To Streamline the Conference Review Process: Experiences from SIGKDD'09</strong></a>. <em>SIGKDD Explorations</em>, 11, (pp. 63-67), 2009.
      </p>
    </td>
  </tr>
</table>

<h2>Videos</h2>

<table>
  <tr>
    <td width="200">
      <a href="[% site.url %]/blog/wapa2010"><img src="[% site.media %]/img/blog/wapa10small.png" width="201" height="126" /></a>
    </td>
    <td width="200">
      <a href="[% site.url %]/blog/peter-flach-talking-about-subsift-at-kdd-09"><img src="[% site.media %]/img/image.jpg" width="201" height="126" /></a>
    </td>
  </tr>
  <tr>
    <td>
      <p>
        <a href="[% site.url %]/blog/wapa2010">Simon Price at WAPA 2010</a>
      </p>
    </td>
    <td>
      <p>
        <a href="[% site.url %]/blog/peter-flach-talking-about-subsift-at-kdd-09">Prof. Peter Flach at KDD 2009</a>
      </p>
    </td>
</table>
