[% 
  page.title = 'Download' 
  page.tab = 'download'
%]


<p>
<a href="http://code.google.com/p/subsift/"><img src="[% site.media %]/img/blog/SubSift-on-Google-Code.png" width="348" height="287" alt="SubSift on Google Code" style="float: right; padding: 0 0 120px 30px;" /></a>
  
You can incorporate SubSift into your own websites, applications and mashups without having to install any software because the software is hosted as a web service with a public API. See the <a href="[% site.url %]/api/">SubSift REST API documentation</a> and <a href="[% site.url %]/doc/">general documentation</a> for further details.</p>

<p>However, SubSift is an <em>open source</em> application distributed via Google Code.
  You can download and install the software to run locally or to modify and incorporate into your own applications.</p>

<p><strong>Download:&nbsp; <a href="http://code.google.com/p/subsift/" class="external">SubSift on Google Code</a></strong></p>

