[% DEFAULT
  page.tab = 'home'
%]

            
            <h2>About SubSift</h2>
            <a href="[% site.url %]/download"><img src="[% site.media %]/img/googlecode.jpg" width="150" height="104" alt="SubSift on Google Code" class="floatRight" /></a>
            <p>SubSift is an innovative "submission sifting" application to support academic peer review. SubSift matches submitted conference or journal papers to potential peer reviewers based on their similarity to published works of prospective reviewers in online bibliographic databases, such as Google Scholar. SubSift is implemented as a collection of web services designed to support not only peer review but also personalised data discovery and mashups in tools like Yahoo! Pipes. SubSift's web services are hosted on this site as a research community resource, but the software itself is also open source and available for <a href="[% site.url %]/download">download</a> from Google Code.</p>
 
            
            <h3 style="margin-bottom:0">Background</h3>
            <p>
              SubSift was developed by the <a href="http://www.bris.ac.uk/ilrt" class="external">IT Services R&amp;D/ILRT</a> at the University of Bristol, based on an innovative application from the <a href="http://intelligentsystems.bristol.ac.uk/" class="external">Intelligent Systems Laboratory</a>. The project was funded by the <a href="http://www.jisc.ac.uk/whatwedo/programmes/inf11/jiscri/subsift" class="external">UK Joint Information Services Council (JISC)</a> under the Rapid Innovation strand of the Information Environment Programme 2009-11. SubSift is part of the University's <a href="http://exabyte.bris.ac.uk/" class="external">Exabyte Informatics Research Theme</a>.
            </p>
            
