[% page.title = 'API Method: bookmark items list'
   page.tab = 'api'
%]

<h2>GET /:user_id/bookmarks/:folder_id/items</h2>
<p>Returns the list of bookmarks (items) from the specified bookmarks folder with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/bookmarks/<em>folder_id</em>/items.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the bookmarks folder to list the items of.
<ul>
<li>Example: <code>[% site.url %]/kdd09/bookmarks/pc/items.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl [% site.url %]/kdd09/bookmarks/pc/items.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <bookmark>
    <name>Ad Feelders</name>
    <created>1266788131</created>
    <description>Ad Feelders</description>
    <modified>1266788131</modified>
    <url>http://dblp.uni-trier.de/search/author?author=Ad%20Feelders</url>
  </bookmark>
  <bookmark>
    <name>Ada Fu</name>
    <created>1266788131</created>
    <description>Ada Fu</description>
    <modified>1266788131</modified>
    <url>http://dblp.uni-trier.de/db/indices/a-tree/f/Fu:Ada_Wai=Chee.html</url>
  </bookmark>
  .
  .
  .
  <bookmark>
    <name>Zoran Obradovic</name>
    <created>1266788131</created>
    <description>Zoran Obradovic</description>
    <modified>1266788131</modified>
    <url>http://dblp.uni-trier.de/search/author?author=Zoran%20Obradovic</url>
  </bookmark>
</result>
[% END %]</pre>
</blockquote>

