[% page.title = 'API Method: bookmark items show'
   page.tab = 'api'
%]

<h2>GET /:user_id/bookmarks/:folder_id/items/:item_id</h2>

<p>Returns a representation of the specified bookmarks item with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/bookmarks/<em>folder_id</em>/items/<em>item_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the bookmarks folder to retrieve from.</li>
<li><code>item_id</code>.  Required. The ID of the bookmark item to retrieve.
<ul>
<li>Example: <code>[% site.url %]/kdd09/bookmarks/pc/items/Peter%20Flach.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl [% site.url %]/kdd09/bookmarks/pc/items/Peter%20Flach.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <bookmark>
    <name>Peter Flach</name>
    <created>1266788131</created>
    <description>Peter A. Flach's homepage</description>
    <modified>1266788131</modified>
    <url>http://www.cs.bris.ac.uk/~flach</url>
  </bookmark>
</result>
[% END %]</pre>
</blockquote>


