[% page.title = 'API Method: bookmarks create'
   page.tab = 'api'
%]

<h2>POST /:user_id/bookmarks/:folder_id</h2>

<p>
Creates a bookmarks folder in the specified user account.
Returns a representation of the created bookmarks folder with a 201 Created HTTP status code.
</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/bookmarks/<em>folder_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>POST</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the bookmarks folder to create.
<ul>
<li>Example: <code>[% site.url %]/kdd09/bookmarks/pc.xml</code></li>
</ul>
</li>
<li><code><em>description</em></code>.  Optional.  The description of the folder to create.</li>
<li><code><em>mode</em></code>.  Optional. Whether the bookmarks folder is publicly accessible or whether authentication is required to access. 
Values can be <code>public</code> or <code>private</code>. Folders are public by default if no mode is specified.</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -X POST -H "Token:mytoken" -d "description=KDD 2009 Programme Committee" [% site.url %]/kdd09/bookmarks/pc.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <folder>
    <id>pc</id>
    <created>1265023664</created>
    <description>KDD 2009 Programme Committee</description>
    <mode>public</mode>
    <modified>1265023664</modified>
  </folder>
</result>
[% END %]</pre>
</blockquote>


