[% page.title = 'SubSift REST API: Calling Methods' 
   page.tab = 'api'
%]

<h2>Calling Methods</h2>

<p>The following pages show how to call SubSift REST API methods from various programming languages.</p>
<ul>
<li><a href="[% site.url %]/api/examples-javascript">JavaScript</a></li>
<li><a href="[% site.url %]/api/examples-prolog">Prolog</a></li>
</ul>

<p>The following page is the first step towards a getting started tutorial.</p>
<ul>
<li><a href="[% site.url %]/api/workflow">SubSift REST API: Example Workflow</a></li>
</ul>

