[% page.title = 'API: cURL' 
   page.tab = 'api'
%]

<p>curl is a command line tool for transferring files with URL syntax, supporting FTP, FTPS, HTTP, HTTPS, SCP, SFTP, TFTP, TELNET, DICT, LDAP, LDAPS and FILE. curl supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP form based upload, proxies, cookies, user+password authentication (Basic, Digest, NTLM, Negotiate, kerberos...), file transfer resume, proxy tunneling and a busload of other useful tricks.</p>

<p>Curl is free and open software that compiles and runs under a wide variety of operating systems.</p>

<p>See <a href="http://curl.haxx.se/" class="external">http://curl.haxx.se</a> for further details.</p>
