[% page.title = 'API Method: document items importing'
   page.tab = 'api'
%]

<h2>HEAD /:user_id/documents/:folder_id/import/:bookmarks_id</h2>

<p>
Tests whether web pages being imported from the specified bookmarks folder into the specified documents folder are still being fetched by SubSift's harvester robot. This method can be polled to detect when the SubSift harvester robot has fetched all the requested web pages. Do not poll more frequently than every minute.
Returns a 200 OK HTTP status code if there are web pages still to be fetched. Otherwise returns 404 Not Found.
</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/documents/<em>folder_id</em>/import/<em>bookmarks_id</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<p>Irrelevant because no response body is returned.</p>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>HEAD</code> 

<p>Clients that can not issue <code>HEAD</code> requests can use <code>GET</code> with the added parameter <code>_method=HEAD</code></p>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the documents folder into which items are being imported.</li>
<li><code>bookmarks_id</code>.  Optional. The ID of the bookmarks folder id being used to create the document items.
Defaults to the same value as <code>folder_id</code>.
<ul>
<li>Example: <code>[% site.url %]/kdd09/documents/pc/import/pc</code><br/>
<li>Or equivalently, <code>[% site.url %]/kdd09/documents/pc/import</code><br/>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -X HEAD -H "Token:mytoken" [% site.url %]/kdd09/documents/pc/import/pc-senior</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>

<p>
A response header is returned with the result in the HTTP status.
No response body is returned.
</p>


