[% page.title = 'API Method: documents folder show' 
   page.tab = 'api'
%]

<h2>GET /:user_id/documents/:folder_id</h2>

<p>Returns a representation of the specified documents folder with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/documents/<em>folder_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the documents folder to be retrieved.
<ul>
<li>Example: <code>[% site.url %]/kdd09/documents/pc.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl [% site.url %]/kdd09/documents/chairs</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<result>
  <folder>
    <id>chairs</id>
    <created>1273842414</created>
    <description>KDD09 Area Chairs</description>
    <mode>public</mode>
    <modified>1273842875</modified>
  </folder>
</result>
[% END %]</pre>
</blockquote>


