[% page.title = 'API Method: document items show'
   page.tab = 'api'
%]

<h2>GET /:user_id/documents/:folder_id/items/:item_id</h2>

<p>Returns a representation of the specified documents item with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/documents/<em>folder_id</em>/items/<em>item_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the documents folder to retrieve from.</li>
<li><code>item_id</code>.  Required. The ID of the document item to retrieve.</li>
<li><code><em>full</em></code>.  Optional. Whether to include the <code>text</code> data in the returned representation of the item.
Values can be either <code>1</code> for true or <code>0</code> for false. The default is <code>0</code>.
<ul>
<li>Example: <code>[% site.url %]/kdd09/documents/pc/items/Peter%20Flach.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -d "full=1" [% site.url %]/kdd09/documents/pc/items/Peter%20Flach.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <item>
    <name>Peter Flach</name>
    <created>1266788131</created>
    <description>Peter A. Flach's homepage</description>
    <id>Peter_Flach</id>
    <modified>1266788131</modified>
    <source>http://www.cs.bris.ac.uk/~flach</source>
    <text>&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
  &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en-gb&quot; xml:lang=&quot;en-gb&quot;&gt;
&lt;head&gt;
   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;application/xhtml+xml; charset=UTF-8&quot; /&gt;
   &lt;link type='text/css' rel='stylesheet' href='/styles/cscontent.css' /&gt;
   &lt;link type='text/css' rel='stylesheet' href='/styles/csmain.css' /&gt;
   &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/styles/niftyCorners.css&quot; /&gt;
   &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/styles/niftyPrint.css&quot; media=&quot;print&quot; /&gt;
   &lt;link rel='icon' id='csbrislink' href='/images/logo.ico' /&gt;
.
.
.      
&lt;div class='legals'&gt;
   &lt;a
href='http://www.bris.ac.uk/university/web/terms_conditions.html#copyright'
class='navlink'&gt;&amp;copy; 1995-2007 University of Bristol&lt;/a&gt;
   &lt;span class='navsep'&gt;&amp;nbsp;|&amp;nbsp;&lt;/span&gt;
   &lt;a href='http://www.bris.ac.uk/university/web/terms_conditions.html'
class='navlink'&gt;Terms and Conditions&lt;/a&gt;
&lt;/div&gt;
&lt;div class='pageinfo'&gt;
   &lt;a href='/lib/about.jsp' class='navlink'&gt;About this Page&lt;/a&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</text>
  </item>
</result>
[% END %]</pre>
</blockquote>


