[% page.title = 'API Method: profile items show' 
   page.tab = 'api'
%]

<h2>GET /:user_id/profiles/:folder_id/items/:item_id</h2>

<p>Returns a representation of the specified profiles item with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/profiles/<em>folder_id</em>/items/<em>item_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the profiles folder to retrieve from.</li>
<li><code>item_id</code>.  Required. The ID of the profile item to retrieve.</li>
<li><code><em>sort</em></code>.  Optional. Number of the term data column to sort the returned <code>term</code> statistics on.
Numeric data columns are sorted in descending order. Textual data columns are sorted in ascending alphabetical order.
Values of <code>sort</code> must be one of:
<ul>
<li><code>0</code> for <code>name</code>, the term name (i.e. the text of the word or keyword).</li>
<li><code>1</code> for <code>n</code>, the term occurrences (i.e. the number of times the term occurs in the document).</li>
<li><code>2</code> for <code>tf</code>, the term frequency (i.e. the ratio of <code>n</code> to the total number of term occurrences in the document).</li>
<li><code>3</code> for <code>idf</code>, the inverse document frequency (i.e. <em>log</em><sub>2</sub> of the ratio of the total number of documents to the number of documents in which the term occurs).</li>
<li><code>4</code> for <code>tfidf</code>, the tf-idf score (i.e. the product of <code>tf</code> and <code>idf</code>).</li>
<li><code>5</code> for <code>wg</code>, the global term weight (i.e. the weight for this term across all items in the folder).</li>
<li><code>6</code> for <code>wl</code>, the local term weight (i.e. the weight for this term in this item).</li>
<li><code>7</code> for <code>wtfidf</code>, the weighted tf-idf score (i.e. the product of <code>tfidf</code>, <code>wg</code> and <code>wl</code>).</li>
</ul>
The default when no value is supplied is <code>7</code>.
</li>
<li><code><em>full</em></code>.  Optional. Whether to include the <code>term</code> data in the returned representation of the item.
Values can be either <code>1</code> for true or <code>0</code> for false. The default is <code>0</code>.
<ul>
<li>Example: <code>[% site.url %]/kdd09/profiles/pc/items/Peter%20Flach.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -d "full=1" [% site.url %]/kdd09/profiles/pc/items/Peter%20Flach.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <profile>
    <name>Peter Flach</name>
    <created>1268566365</created>
    <description>Peter Flach</description>
    <document_n>1154</document_n>
    <modified>1268566365</modified>
    <source>http://dblp.uni-trier.de/db/indices/a-tree/f/Flach:Peter_A=.html</source>
    <term>
      <name>ilp</name>
      <idf>2.78135971352466</idf>
      <n>14</n>
      <tf>0.0121422376409367</tf>
      <tfidf>0.033771930606544</tfidf>
      <wg>1</wg>
      <wl>1</wl>
      <wtfidf>0.033771930606544</tfidf>
    </term>
    <term>
      <name>roc</name>
      <idf>3.4594316186373</idf>
      <n>11</n>
      <tf>0.00954032957502168</tf>
      <tfidf>0.0330041177840505</tfidf>
      <wg>1</wg>
      <wl>1</wl>
      <wtfidf>0.0330041177840505</tfidf>
    </term>
    <term>
      <name>logic</name>
      <idf>2.05343925896146</idf>
      <n>18</n>
      <tf>0.01561144839549</tf>
      <tfidf>0.0320571610245501</tfidf>
      <wg>1</wg>
      <wl>1</wl>
      <wtfidf>0.0320571610245501</tfidf>
    </term>
    .
    .
    .
    <term>
      <name>conferences</name>
      <idf>0</idf>
      <n>1</n>
      <tf>0.000867302688638335</tf>
      <tfidf>0</tfidf>
      <wg>1</wg>
      <wl>1</wl>
      <wtfidf>0</tfidf>
    </term>
  </profile>
</result>
[% END %]</pre>
</blockquote>


