[% page.title = 'API Method: profiles show' 
   page.tab = 'api'
%]

<h2>GET /:user_id/profiles/:folder_id</h2>

<p>Returns a representation of the specified profiles folder with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/profiles/<em>folder_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the profiles folder to be retrieved.</li>
<li><code>sort</code>.  Optional. Number of the term data column to sort the returned <code>term</code> statistics on.
Numeric data columns are sorted in descending order. Textual data columns are sorted in ascending alphabetical order.
Values of <code>sort</code> must be one of:
<ul>
<li><code>0</code> for <code>name</code>, the term name (i.e. the text of the word or keyword)</li>
<li><code>1</code> for <code>n</code>, the term occurrences (i.e. the total number of times a term occurs across all items in the document)</li>
<li><code>2</code> for <code>dt</code>, the document term count (i.e. the total number items in the document in which the term occurs)</li>
</ul>
The default when no value is supplied is <code>2</code>.
</li>
<li><code><em>full</em></code>.  Optional. Whether to include the <code>term</code> data in the returned representation of the folder of the profiles folder.
Values can be either <code>1</code> for true or <code>0</code> for false. The default is <code>0</code>.
<ul>
<li>Example: <code>[% site.url %]/kdd09/profiles/pc.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -d "full=1" [% site.url %]/kdd09/profiles/pc</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <folder>
    <id>pc</id>
    <document_id>pc</document_id>
    <created>1266793611</created>
    <description>KDD09 Programme Committee</description>
    <ignore_case>1</ignore_case>
    <limit>100000</limit>
    <mode>private</mode>
    <modified>1268566365</modified>
    <ngrams>1,2</ngrams>
    <remove_html>1</remove_html>
    <remove_stopwords>1</remove_stopwords>
    <stopwords>paper,position paper,short paper, ... ,proceedings</stopwords>
    <term>
      <name>faq</name>
      <dt>220</dt>
      <n>432</n>
    </term>
    <term>
      <name>author</name>
      <dt>220</dt>
      <n>238</n>
    </term>
    <term>
      <name>home</name>
      <dt>220</dt>
      <n>225</n>
    </term>
    .
    .
    .
    <term>
      <name>timescale</name>
      <dt>1</dt>
      <n>1</n>
    </term>
    <term>
      <name>schism</name>
      <dt>1</dt>
      <n>2</n>
    </term>
    <threshold>0</threshold>
  </folder>
</result>
[% END %]</pre>
</blockquote>


