[% page.title = 'API Method: reports list'
   page.tab = 'api'
%]

<h2>GET /:user_id/reports</h2>
<p>Returns a list of reports folders with a 200 OK HTTP status code.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/reports.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl [% site.url %]/kdd09/reports.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <folder>
    <id>chairs_profiles</id>
    <created>1293480606</created>
    <description>Profiles of KDD09 Area Chairs</description>
    <mode>public</mode>
    <modified>1293480606</modified>
    <profiles_id>chairs</profiles_id>
  </folder>
  <folder>
    <id>pc_papers_matches</id>
    <created>1293480802</created>
    <description>Matches between KDD09 Programme Committee and papers</description>
    <matches_id>pc_papers</matches_id>
    <mode>private</mode>
    <modified>1293480802</modified>
  </folder>
  .
  .
  .
</result>
[% END %]</pre>
</blockquote>

