[% page.title = 'API Method: reports folder show' 
   page.tab = 'api'
%]

<h2>GET /:user_id/reports/:folder_id.:format</h2>

<p>Returns a representation of the specified reports folder with a 200 OK HTTP status code.
  Note that the <code>:format</code> file extension must be specified or else the file <code>index.html</code>
  from the results folder (i.e. the reports homepage) will be returned instead.</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/reports/<em>folder_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>GET</code>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code> &nbsp;if folder's <code>mode</code> property is set to <code>private</code><br/>
<code>false</code> &nbsp;if folder's <code>mode</code> property is set to <code>public</code>

<h3>Parameters:</h3>
<ul>
<li><code>folder_id</code>.  Required. The ID of the reports folder to be retrieved.
<ul>
<li>Example: <code>[% site.url %]/kdd09/reports/pc_profiles.xml</code></li>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl [% site.url %]/kdd09/reports/chairs_profiles.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<result>
  <folder>
    <id>chairs_profiles</id>
    <created>1293480606</created>
    <description>Profiles of KDD09 Area Chairs</description>
    <mode>public</mode>
    <modified>1293480606</modified>
    <profiles_id>chairs</profiles_id>
  </folder>
</result>
[% END %]</pre>
</blockquote>


