[% page.title = 'API Method: workflow destroy'
   page.tab = 'api'
%]

<h2>DELETE /:user_id/workflow/:workflow_id</h2>

<p>
Deletes the specified workflow. 
Returns the string "ok" with a 200 OK HTTP status code.
</p>

<h3>URL:</h3>
<code>[% site.url %]/<em>user_id</em>/workflow/<em>workflow_id</em>.<em>format</em></code>

<h3>Formats (<a href="formats">about return formats</a>):</h3>
<code>[% INCLUDE 'api/_formats.phtml' %]</code>

<h3>HTTP Methods (<a href="http-methods">about HTTP methods</a>):</h3>
<code>DELETE</code>
<p>Clients that can not issue <code>DELETE</code> requests can use <code>POST</code> with the added parameter <code>_method=DELETE</code></p>

<h3>Requires Authentication (<a href="authentication">about authentication</a>):</h3>
<code>true</code>

<h3>Parameters:</h3>
<ul>
<li><code>workflow_id</code>.  Required. The ID of the workflow to destroy.</li>
<ul>
<li>Example: <code>[% site.url %]/kdd09/workflow/myflow1</code>
</ul>
</li>
</ul>

<h3>Usage Examples:</h3>
<blockquote>
<h4>cURL (<a href="curl">about cURL</a>):</h4>
<code>curl -X DELETE -H "Token:mytoken" [% site.url %]/kdd09/workflow/myflow1.xml</code><br/>
</blockquote>

<h3>Response (<a href="return-values">about return values</a>):</h3>
<blockquote>
<h4>XML example:</h4>
<pre>[% FILTER html -%]
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <value>ok</value>
</result>[% END %]</pre>
</blockquote>


